name: EP Send souurce to publish site

on:
  push:
    branches:
    - main
jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pushes to public repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@ssh-deploy-key
        env:
          SSH_DEPLOY_KEY: ${{ secrets.WORKFLOW_DEPLOY_KEY }}
        with:
          source-directory: _site/
          destination-github-username: 'nriquedev'
          destination-repository-name: 'nriquedev.github.io'
          user-email: nriquedev@gmail.com
          commit-message: pushed from $GITHUB_REF
          target-branch: master